kubernetes/caasp: Fix path to admin.conf file
When calling kubectl, a configuration file needs to be given. We use
the one stored in self._kubeconfig but skuba is downloading that into
the $workspace/cluster/ directory instead of $workspace/ . So fixing
the path here.
This fixes:

subprocess.CalledProcessError: Command '/usr/bin/kubectl \
  --kubeconfig /tmp/rookcheck/tom-rookci-db6860aa/admin.conf \
  get pods --all-namespaces' returned non-zero exit status 1.

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>