tests_basic: Download direct-mount.yaml if not available
With the SES7 rook rpm package, the direct-mount.yaml rook/ceph
example is not available from the rpm package.
In that case, download the file from github and use it for testing.
Without that, running the basic tests with SES7 fails with:

10:38:44 kubectl apply -f /home/tom/tmp/rookcheck/rook WARNING : \
  error: the path "/home/tom/tmp/rookcheck/rookcheck-tom-0ac2/\
  rook/ceph/direct-mount.yaml" does not exist