config: Include libvirt.toml config
It's needed to have the libvirt variables available when using the
libvirt backend. Otherwise it fails with:

dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has \
  no attribute 'network_range'"

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>