Revert "Add more structure rook code"
This breaks the CaaSP kubernetes deployment with:

ModuleNotFoundError: No module named 'tests.lib.rook.ses'

This reverts commit 43c122e9550bae6e02b894dbf4de073ca64cfb38.