hardware/openstack_libcloud: Boot the node during node_create()
That's similar to what's done in the libvirt implementation. With
that, a floating IP is available after node_create() is called.
This fixes:

  IndexError: list index out of range
  tests/lib/hardware/hardware_base.py:106: in node_add
      self._node_remove_ssh_key(node)
  tests/lib/hardware/hardware_base.py:82: in _node_remove_ssh_key
      f"Removing {node.get_ssh_ip()} from known-hosts if exists.")

when trying to access a floating IP that is not available

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>