hardware/libvirt: add lock for libvirt defineXML
On some version of libvirt the "Duplicate key" internal error occurs
while trying to define a node in parallel, for example:

    Traceback (most recent call last):
      File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/lib64/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 400, in _boot_node
        node = self.node_create(name, role, tags)
      File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 396, in node_create
        node.boot()
      File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 75, in boot
        self._dom = self._conn.defineXML(xml)
      File "/home/kyr/suse/rookcheck/.tox/py36/lib64/python3.6/site-packages/libvirt.py", line 4049, in defineXML
        if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
    libvirt.libvirtError: internal error: Duplicate key

This patch adds a workaround for it.

Fixes: https://github.com/SUSE/rookcheck/issues/161

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>